# Generated by Django 2.2.6 on 2019-10-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('tipo', models.CharField(choices=[('Alimentício', 'Alimentício'), ('Veterinário', 'Veterinário'), ('Beleza', 'Beleza')], default='Alimentício', max_length=40)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['descricao'],
            },
        ),
    ]
